In [2]:
import cv2

In [ ]:
# create a cascadeClassifier object 
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

# Reading the image as it is
img = cv2.imread("arms-crossed-confident-facial-expression-2379004.jpg",1) # 1 for colour image  

# Reading the image as a gray scale image
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# Search the co-ordintes of the image 
faces = face_cascade.detectMultiScale(gray_img,scaleFactor = 1.05,minNeighbors =5)
print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

resize_image = cv2.resize(img,(int(img.shape[1]/4),int(img.shape[0]/4)))
    
cv2.imshow("Gray",resize_image)

cv2.waitKey(0)

cv2.destroyAllWindows()



<class 'numpy.ndarray'>
[[ 467  621   30   30]
 [ 691  719  635  635]
 [ 115 2004  104  104]
 [ 200 2115   29   29]
 [ 402 2489   50   50]
 [ 350 2402   84   84]
 [  51 2584   27   27]
 [ 389 2513   84   84]]


In [4]:
# create a cascadeClassifier object 
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt2.xml")

# Reading the image as it is
img = cv2.imread("arms-crossed-confident-facial-expression-2379004.jpg",1) # 1 for colour image  

# Reading the image as a gray scale image
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# Search the co-ordintes of the image 
faces = face_cascade.detectMultiScale(gray_img,scaleFactor = 1.05,minNeighbors =5)
print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

resize_image = cv2.resize(img,(int(img.shape[1]/4),int(img.shape[0]/4)))
    
cv2.imshow("Gray",resize_image)

cv2.waitKey(0)

cv2.destroyAllWindows()



<class 'numpy.ndarray'>
[[700 735 615 615]]


In [ ]:
# create a cascadeClassifier object 
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_alt2.xml")

# Reading the image as it is
img = cv2.imread("arms-crossed-confident-facial-expression-2379004.jpg",1) # 1 for colour image  

# Reading the image as a gray scale image
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# Search the co-ordintes of the image 
faces = face_cascade.detectMultiScale(gray_img,scaleFactor = 1.05,minNeighbors =5)
print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

resize_image = cv2.resize(img,(int(img.shape[1]/4),int(img.shape[0]/4)))
    
cv2.imshow("Gray",resize_image)

cv2.waitKey(0)

cv2.destroyAllWindows()



In [5]:
# create a cascadeClassifier object 
face_cascade = cv2.CascadeClassifier("haarcascade_fullbody.xml")

# Reading the image as it is
img = cv2.imread("arms-crossed-confident-facial-expression-2379004.jpg",1) # 1 for colour image  

# Reading the image as a gray scale image
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# Search the co-ordintes of the image 
faces = face_cascade.detectMultiScale(gray_img,scaleFactor = 1.05,minNeighbors =5)
print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

resize_image = cv2.resize(img,(int(img.shape[1]/4),int(img.shape[0]/4)))
    
cv2.imshow("Gray",resize_image)

cv2.waitKey(0)

cv2.destroyAllWindows()



<class 'numpy.ndarray'>
[[1260  778   39   78]
 [1038 1183   31   61]]


In [3]:
# create a cascadeClassifier object 
face_cascade = cv2.CascadeClassifier("haarcascade_upperbody.xml")

# Reading the image as it is
img = cv2.imread("arms-crossed-confident-facial-expression-2379004.jpg",1) # 1 for colour image  

# Reading the image as a gray scale image
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# Search the co-ordintes of the image 
faces = face_cascade.detectMultiScale(gray_img,scaleFactor = 1.05,minNeighbors =5)
print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

resize_image = cv2.resize(img,(int(img.shape[1]/4),int(img.shape[0]/4)))
    
cv2.imshow("Gray",resize_image)

cv2.waitKey(0)

cv2.destroyAllWindows()



<class 'tuple'>
()
